/* 
  _______ _______ _______     _______  ___  ___ __      __       __ 
 |   _   |   _   |   _   |   |   _   .'  _.'  _|__.----|__.-----|  |
 |.  1___|.  1   |___|   |   |.  |   |   _|   _|  |  __|  |  -__|  |
 |.  |___|.  ____|/  ___/    |.  |   |__| |__| |__|____|__|_____|__|
 |:  1   |:  |   |:  1  \    |:  1   | Version 1.0                       
 |::.. . |::.|   |::.. . |   |::.. . | By XlaTor & SkyX-ID-FR                               
 `-------`---'   `-------'   `-------'   
*/

import Head from 'next/head';
import NavBar from 'components/NavBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>CPZ Officiel© - Accueil</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="https://zupimages.net/up/23/04/eb3o.png"/>
      </Head>

      <div className='home_page'>
        <NavBar/>

        <section id="content_box">
          <div className='ads'><p>-10% avec le code CALEÇON - Valable jusqu'au 15 Mars 2023</p></div>
          <p>content_box</p>
        </section>
      </div>
    </>
  )
}
